project_id = "yqslvnsdqpsosqghpenq"

[functions.populate-content-counts]
verify_jwt = false

[functions.get-trending-shows]
verify_jwt = true

[functions.binge-bot-chat]
verify_jwt = true

[functions.earn-binge-points]
verify_jwt = true

[functions.tvdb-proxy]
verify_jwt = false

[functions.trakt-proxy]
verify_jwt = false
